route:
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'default'
  routes:
    - matchers:
        - severity="critical"
      receiver: 'critical'
      continue: true
    - matchers:
        - severity="warning"
      receiver: 'default'

receivers:
  - name: 'default'
  - name: 'critical'

inhibit_rules:
  - source_matchers:
      - severity="critical"
    target_matchers:
      - severity="warning"
    equal: ['alertname']
