apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    uid: prometheus

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    uid: loki
    jsonData:
      maxLines: 1000

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: true
    uid: tempo
    jsonData:
      tracesToLogs:
        datasourceUid: loki
        tags: ['service.name', 'http.route', 'http.status_code']
        mappedTags:
          - key: service.name
            value: service_name
        mapTagNamesEnabled: true
        spanEndTimeShift: '-30m'
        spanStartTimeShift: '30m'
      serviceMap:
        datasourceUid: prometheus
